### ISSUE TITLE
Initialize API and Setup Basic Server

### ISSUE THREAD

**Issue by CodeRoadSoftwares** [CodeRoadSoftwares/tealthy#2]
This task involves initializing the API for Tealthy by installing necessary packages such as Express, CORS, and Body-parser. Additionally, you will set up the basic server with all necessary middlewares to handle incoming requests. The goal is to establish the API infrastructure and create a solid foundation for further development and integration with the frontend.

**Comment by MouzinGulzar** [comment]
Add connection to database. @Suraj-Prakash-Singh
