### ISSUE TITLE
Implement Doctor Overview Card and Button Components

### ISSUE THREAD

**Issue by CodeRoadSoftwares** [CodeRoadSoftwares/tealthy#3]
Create and integrate the Doctor Overview Card component, which will display key information about doctors, including their name, specialization, rating, and total appointments taken. The card should have a clean and professional design, following Material-UI guidelines.

In addition, design and implement three types of buttons:
- **Primary Button:** Used for important actions like form submission or critical decisions.
- **Secondary Button:** For less prominent actions that are still important.
- **Call-to-Action Button:** Designed to prompt an immediate response from the user.

Ensure that all buttons have consistent styling and are easily distinguishable from each other. These components should be responsive and enhance the overall user experience of the application.

### Deliverables:
- Doctor Overview Card component with dynamic content.
- Primary, Secondary, and Call-to-Action buttons with consistent styling.

**Comment by MouzinGulzar** [comment]
Moreover use Styled Components to implement custom styles.

**Comment by CodeRoadSoftwares** [comment]
#11
